default_connection: mysql
mysql:
    name: mysqlStorage
    driver: pdo_mysql
    dbhost: localhost
    dbuser: telegrambot
    dbpass: telegrambot
    dbname: telegrambots
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
    extra_types:
        uuid: \Ramsey\Uuid\Doctrine\UuidType
        uuid_binary: \Ramsey\Uuid\Doctrine\UuidBinaryType
